apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-riker
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: team-riker
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: https://github.com/praneeth2k3/eks-blueprints-workloads
    targetRevision: main
    path: teams/team-riker/dev
    helm:
      parameters:
      - name: spec.ingress.host
        value: {{ .Values.spec.ingress.host }}
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
